language: python
python:
    - "3.7"
node_js:
    - "10"
cache:
    yarn: true
    pip: true
    directories:
        - node_modules
install:
    - pip install poetry
    - poetry install
script:
    - poetry run pytest
after_script:
    - yarn global add danger
    - poetry run danger-python ci
